-- World Patro admin schema, to be applied ONLY to a dedicated World Patro Supabase project.
-- DO NOT apply to jhuto-com or any other project. Reviewed design 2026-10-09.
-- This script can be run once after confirming the correct Supabase project reference.
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists public.admin_content (
 id text primary key,
 kind text not null check(kind in ('source','authority','observance','article')),
 title text not null check(char_length(title) between 3 and 160),
 slug text not null check(slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
 summary text not null default '',
 body text not null default '',
 source_url text not null default '',
 country text not null default '',
 tradition text not null default '',
 event_date text not null default '',
 status text not null default 'draft' check(status in ('draft','in_review','published','archived')),
 version integer not null default 1 check(version>=1),
 created_by text not null,
 updated_by text not null,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 constraint admin_content_id_canonical check(id=kind||'__'||slug),
 constraint admin_published_metadata check (
   status <> 'published' or
   (length(trim(summary))>0 and length(trim(body))>0 and source_url like 'https://%')
 )
);
create index if not exists admin_content_kind_status_idx on public.admin_content(kind,status);
create index if not exists admin_content_updated_idx on public.admin_content(updated_at desc);
alter table public.admin_content enable row level security;
revoke all on public.admin_content from anon,authenticated;
grant select on public.admin_content to anon,authenticated;
grant insert,update on public.admin_content to authenticated;

create table if not exists public.admin_audit_log(
 id bigint generated by default as identity primary key,
 record_id text not null,
 kind text not null,
 action text not null check(action in ('create','update')),
 actor_id text not null,
 old_status text,
 new_status text,
 version integer not null,
 changed_fields text[] not null default '{}',
 created_at timestamptz not null default now()
);
create index if not exists admin_audit_created_idx on public.admin_audit_log(created_at desc);
alter table public.admin_audit_log enable row level security;
revoke all on public.admin_audit_log from anon,authenticated;
grant select on public.admin_audit_log to authenticated;

create policy "published records public" on public.admin_content for select to anon
  using(status='published');
create policy "authenticated published or trusted editorial roles" on public.admin_content
  for select to authenticated
  using(status='published' or
    (auth.jwt()->'app_metadata'->>'worldpatro_role') in ('admin','editor','reviewer'));
create policy "admin can create draft" on public.admin_content for insert to authenticated
  with check (
    auth.uid() is not null and
    (auth.jwt()->'app_metadata'->>'worldpatro_role')='admin'
    and status='draft'
    and created_by=auth.uid()::text and updated_by=auth.uid()::text
  );
create policy "admin update" on public.admin_content for update to authenticated
  using (
    auth.uid() is not null and
    (auth.jwt()->'app_metadata'->>'worldpatro_role')='admin'
  )
  with check (
    auth.uid() is not null and
    (auth.jwt()->'app_metadata'->>'worldpatro_role')='admin'
    and updated_by=auth.uid()::text
  );
create policy "trusted editor reads audit" on public.admin_audit_log for select to authenticated
  using ((auth.jwt()->'app_metadata'->>'worldpatro_role') in ('admin','editor','reviewer'));

create or replace function private.enforce_admin_record_transition()
returns trigger language plpgsql security invoker set search_path='' as $$
begin
  if new.kind <> old.kind or new.slug <> old.slug or new.id <> old.id
    or new.created_by <> old.created_by or new.created_at <> old.created_at then
    raise exception 'Identity and creation fields are immutable';
  end if;
  if new.version <> old.version + 1 then
    raise exception 'Version must advance by exactly one';
  end if;
  if new.status <> old.status and not (
    (old.status='draft' and new.status='in_review') or
    (old.status='in_review' and new.status in ('draft','published')) or
    (old.status='published' and new.status='archived') or
    (old.status='archived' and new.status='draft')
  ) then
    raise exception 'Invalid publication transition';
  end if;
  if new.status='published' and
    (length(trim(new.summary))=0 or length(trim(new.body))=0 or new.source_url not like 'https://%') then
    raise exception 'A published record must be complete and source-linked';
  end if;
  new.updated_at=now();
  return new;
end $$;
create trigger enforce_admin_record_transition before update on public.admin_content
for each row execute function private.enforce_admin_record_transition();

create or replace function private.audit_admin_record_change()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  insert into public.admin_audit_log
    (record_id,kind,action,actor_id,old_status,new_status,version,changed_fields)
  values
    (new.id,new.kind,case when TG_OP='INSERT' then 'create' else 'update' end,
     coalesce(auth.uid()::text,'UNKNOWN'),
     case when TG_OP='INSERT' then null else old.status end,new.status,new.version,
     case when TG_OP='INSERT' then array['created']::text[] else array['updated']::text[] end);
  return new;
end $$;
revoke all on function private.audit_admin_record_change() from public,anon,authenticated;
create trigger audit_admin_content_insert after insert on public.admin_content
for each row execute function private.audit_admin_record_change();
create trigger audit_admin_content_update after update on public.admin_content
for each row execute function private.audit_admin_record_change();

-- No DELETE grants/policy. Archive is the supported soft-delete with audit retention.
-- Never bootstrap an admin from email, client-set user_metadata or a public endpoint.
